# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mystargram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mystargram

  pod 'Alamofire', '~> 5.1'
  pod 'SDWebImage'

  target 'mystargramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mystargramUITests' do
    # Pods for testing
  end

end
